Moved apt check to ubuntu install

diff --git a/default/scripts/install/ubuntu b/default/scripts/install/ubuntu
--- a/default/scripts/install/ubuntu
+++ b/default/scripts/install/ubuntu
@@ -11,6 +11,11 @@ if [[ "$EUID" -ne "0" ]]; then
   exit 1
 fi
 
+if [[ $(command -v add-apt-repository) == "" ]]; then
+  printf "\033[0;31m\nadd-apt-repository not found, aborting\033[0m\n"
+  exit 1
+fi
+
 while getopts "v" OPT; do
   case "${OPT}" in
     v)
